server.port: ${port}

logging:
  level.root: ${log.level}
log:
  path: ${log.path}

spi:
  user:
    impl:
      class: ${spi.user.impl.class}

spring:
  datasource:
    url: ${datasource.url}
    password: ${datasource.password}
    username: ${datasource.username}
    driver-class-name: ${datasource.driver-class-name}
  application:
    name: IM

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

  ldap:
    base: "dc=example,dc=org"
    username: "cn=admin,dc=example,dc=org"
    password: "password"
    searchFilter: "(uid={0})"
    urls:
      - "ldap://localhost:389"

ldap:
  mapping:
    objectClass:
    loginId: "uid"
    userDisplayName:
    email: "mail"
  filter:
  memberOf: "cn=ServiceDEV,ou=DEV,dc=example,dc=org|cn=WebDEV,ou=DEV,dc=example,dc=org"