server.port: ${port}

logging:
  level.root: ${log.level}
log:
  path: ${log.path}

spi:
  user:
    impl:
      class: ${spi.user.impl.class}

spring:
  datasource:
    url: ${datasource.url}
    password: ${datasource.password}
    username: ${datasource.username}
    driver-class-name: ${datasource.driver-class-name}
  application:
    name: IM

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

  ldap:
    base: ${ldap.base}
    username: ${ldap.username}
    password: ${ldap.password}
    searchFilter: ${ldap.searchFilter}
    urls: ${ldap.urls}

ldap:
  searchBase: ${ldap.searchBase}
  mapping:
    objectClass: ${ldap.mapping.objectClass}
    loginId: ${ldap.mapping.loginId}
    userDisplayName: ${ldap.mapping.userDisplayName}
    email: ${ldap.mapping.email}