server.port: ${port}

logging:
  level.root: ${log.level}
log:
  path: ${log.path}

spi:
  user:
    impl:
      class: ${spi.user.impl.class}

spring:
  datasource:
    url: ${datasource.url}
    password: ${datasource.password}
    username: ${datasource.username}
    driver-class-name: ${datasource.driver-class-name}
  application:
    name: IM

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

#  ldap:
#    base: ${ldap.base}
#    username: ${ldap.username}
#    password: ${ldap.password}
#    searchFilter: ${ldap.searchFilter}
#    urls: ${ldap.urls}
#
#ldap:
#  mapping:
#    objectClass: ${ldap.mapping.objectClass}
#    loginId: ${ldap.mapping.loginId}
#    userDisplayName: ${ldap.mapping.userDisplayName}
#    email: ${ldap.mapping.email}
#  filter:
#    memberOf: "cn=ServiceDEV,ou=DEV,dc=example,dc=org|cn=WebDEV,ou=DEV,dc=example,dc=org"
#  group:
#    objectClass: "groupOfNames" # 配置groupClassName
#    groupBase: "ou=group" # group search base
#    groupSearch: "(&(cn=dev))" # group filter
#    groupMembership: "member" # group memberShip eg